# Optional overrides (you can remove if unused)
SHEET_ID = "1PLpxXH1cE6Xe6BefvfaeO6eN0SwpHwuH0KY-Kocp-l4"
DRIVE_PARENT_ID_DEFAULT = "YOUR_SHARED_DRIVE_FOLDER_ID"

# Your Google Service Account credentials (keep this private!)
gcp_service_account = "<<REDACTED - provide via Streamlit secrets or local service_account.json>>"